# File: .github/workflows/deploy_terraform.yml

name: "Deploy Terraform with Shared Workflow"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    

jobs:
  call-terraform:
    uses: muna1991/Terrform-Library/.github/workflows/terraform.yml@main  # Reference to the shared workflow
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
