# File: .github/workflows/terraform_s3_bucket.yml

name: "Terraform S3 Bucket Deployment"

on:
  workflow_call: # Enables this workflow to be reusable
    inputs:
      aws_access_key_id:
        required: true
        type: string
      aws_secret_access_key:
        required: true
        type: string
      aws_session_token:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false

jobs:
  terraform:
    runs-on: self-hosted
    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      AWS_SESSION_TOKEN: ${{ inputs.aws_session_token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Terraform Initialization
        run: terraform init

      - name: Terraform Planning
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
